# Generated by Django 2.1.5 on 2019-01-20 20:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=16)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('average_rating', models.FloatField(default='0')),
                ('link', models.URLField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, max_length=1024)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='test_image')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='BusinessLatLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=512)),
                ('relevance', models.FloatField(default=0)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choice', multiselectfield.db.fields.MultiSelectField(choices=[('day_camps', 'Day Camps'), ('residential_camps', 'Residential Camps'), ('track_out_program', 'Track-Out Programs'), ('half_day', 'Half-Day'), ('full_day', 'Full-Day'), ('academics', 'Academics'), ('animal_care', 'Animal Care'), ('arts_crafts', 'Arts & Crafts'), ('cooking_baking', 'Cooking & Baking'), ('games', 'Games'), ('health_fitness', 'Health & Fitness'), ('outdoor_play_nature', 'Outdoor & Nature'), ('performing_arts', 'Performing Arts'), ('sports', 'Sports'), ('technology', 'Technology'), ('other', 'Other')], max_length=193, null=True)),
                ('age_choice', models.CharField(choices=[('all_ages', 'All Ages'), ('preschool', 'Pre-K'), ('k_5', 'Elementary'), ('middle_school', 'Middle School'), ('high_school', 'High School')], max_length=20, null=True)),
                ('class_camp_choice', models.CharField(choices=[('class', 'Class'), ('camp', 'Camp'), ('homeschool', 'Homeschool')], max_length=10, null=True)),
                ('cities_choice', models.CharField(choices=[('raleigh', 'Raleigh'), ('durham', 'Durham'), ('cary', 'Cary'), ('chapel_hill', 'Chapel Hill'), ('morrisville', 'Morrisville'), ('rtp', 'RTP'), ('carrboro', 'Carrboro')], max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='test_image')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Business')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='LeaveReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=75)),
                ('event', models.CharField(blank=True, max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.Business')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
