# Generated by Django 2.1.5 on 2019-01-15 02:27

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geom',
            field=djgeojson.fields.PointField(blank=True),
        ),
    ]
