# Generated by Django 2.1.5 on 2019-01-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(blank=True, choices=[('PRE-K', 'Pre-K'), ('ELEMENTARY', 'Elementary'), ('MIDDLE', 'Middle'), ('HIGH', 'High')], max_length=12, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='ages',
            field=models.ManyToManyField(related_name='events', to='core.Age'),
        ),
    ]
