# Generated by Django 2.1.5 on 2019-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_leavereview_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('stereo', 'Stereo')], max_length=50, null=True),
        ),
    ]
