# Generated by Django 2.1.5 on 2019-01-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='geom',
            new_name='list',
        ),
    ]
