# Generated by Django 2.1.5 on 2019-01-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190115_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='list',
        ),
    ]
