# Generated by Django 2.1.5 on 2019-01-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
    ]
