# Generated by Django 2.1.5 on 2019-01-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_event_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='geom',
        ),
    ]
