# Generated by Django 2.1.5 on 2019-01-09 17:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('half_day', 'Half-Day'), ('full_day', 'Full-Day'), ('academic', 'Academic'), ('arts_crafts', 'Arts & Crafts'), ('athletics', 'Athletics'), ('games', 'Games'), ('language', 'Language'), ('nature_outdoor', 'Nature/Outdoor'), ('performance', 'Performance'), ('stem', 'STEM'), ('other', 'Other')], max_length=101, null=True),
        ),
    ]
