# Generated by Django 2.1.5 on 2019-01-15 03:34

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mushroomspot_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='geom',
            field=djgeojson.fields.PointField(blank=True),
        ),
    ]
