# Generated by Django 2.1.5 on 2019-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_choice',
            field=models.CharField(choices=[('pre_k', 'Pre-K'), ('elementary', 'Elementary'), ('middle', 'Middle'), ('high', 'High')], max_length=20, null=True),
        ),
    ]
