# Generated by Django 2.1.5 on 2019-01-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_age_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cities_choice',
            field=models.CharField(choices=[('raleigh', 'Raleigh'), ('durham', 'Durham'), ('cary', 'Cary'), ('chapel_hill', 'Chapel Hill')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='class_camp_choice',
            field=models.CharField(choices=[('class', 'Class'), ('camp', 'Camp')], max_length=10, null=True),
        ),
    ]
