# Generated by Django 2.1.5 on 2019-01-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190109_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_choice',
            field=models.CharField(choices=[('pre-k', 'Pre-K'), ('elementary', 'Elementary'), ('middle', 'Middle'), ('high', 'High')], max_length=20, null=True),
        ),
    ]
