# Generated by Django 2.1.5 on 2019-01-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190110_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereview',
            name='rating',
            field=models.PositiveIntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='0'),
        ),
    ]
