# Generated by Django 2.1.5 on 2019-01-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190110_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereview',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
