# Generated by Django 2.1.5 on 2019-01-10 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190110_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
