# Generated by Django 2.1.5 on 2019-01-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190110_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cities_choice',
            field=models.CharField(choices=[('raleigh', 'Raleigh'), ('durham', 'Durham'), ('cary', 'Cary'), ('chapel_hill', 'Chapel Hill'), ('morrisville', 'Morrisville'), ('rtp', 'RTP'), ('carrboro', 'Carrboro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='class_camp_choice',
            field=models.CharField(choices=[('class', 'Class'), ('camp', 'Camp'), ('homeschool', 'Homeschool')], max_length=10, null=True),
        ),
    ]
