# Generated by Django 2.1.5 on 2019-01-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190111_2126'),
        ('core', '0012_auto_20190111_2125'),
    ]

    operations = [
    ]
