# Generated by Django 2.1.5 on 2019-01-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190114_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
