# Generated by Django 2.1.5 on 2019-01-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_business_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
