# Generated by Django 2.1.5 on 2019-01-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_business_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
