# Generated by Django 2.1.5 on 2019-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mushroomspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
