# Generated by Django 2.1.5 on 2019-01-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190111_2125'),
        ('core', '0016_auto_20190114_0426'),
    ]

    operations = [
    ]
