# Generated by Django 2.1.5 on 2019-01-13 01:31

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190113_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='geom',
            field=djgeojson.fields.PointField(blank=True),
        ),
    ]
