# Generated by Django 2.1.5 on 2019-01-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20190115_1520'),
        ('core', '0017_merge_20190115_1524'),
    ]

    operations = [
    ]
