# Generated by Django 2.1.5 on 2019-01-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_businesslatlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslatlong',
            name='location_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='businesslatlong',
            name='relevance',
            field=models.FloatField(default=0),
        ),
    ]
