# Generated by Django 2.1.5 on 2019-01-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190113_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='address',
        ),
    ]
