# Generated by Django 2.1.5 on 2019-01-16 14:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20190115_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, upload_to='test_image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('academic', 'Academic'), ('arts_crafts', 'Arts & Crafts'), ('athletics', 'Athletics'), ('games', 'Games'), ('language', 'Language'), ('nature_outdoor', 'Nature/Outdoor'), ('performance', 'Performance'), ('stem', 'STEM'), ('other', 'Other')], max_length=83, null=True),
        ),
    ]
