# Generated by Django 2.1.5 on 2019-01-16 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190116_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslatlong',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Business', unique=True),
        ),
    ]
