# Generated by Django 2.1.5 on 2019-01-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mushroomspot_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='address',
        ),
    ]
