# Generated by Django 2.1.5 on 2019-01-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190116_1407'),
        ('core', '0020_auto_20190116_0304'),
    ]

    operations = [
    ]
