# Generated by Django 2.1.5 on 2019-01-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20190116_1525'),
        ('core', '0021_merge_20190116_1526'),
    ]

    operations = [
    ]
