# Generated by Django 2.1.5 on 2019-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_mushroomspot_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
