# Generated by Django 2.1.5 on 2019-01-13 18:18

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mushroomspot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroomspot',
            old_name='geom',
            new_name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=djgeojson.fields.PointField(blank=True),
        ),
    ]
