# Generated by Django 2.1.5 on 2019-01-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20190116_1525'),
        ('core', '0022_auto_20190116_1744'),
        ('core', '0022_auto_20190116_2032'),
    ]

    operations = [
    ]
