# Generated by Django 2.1.5 on 2019-01-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20190116_1543'),
        ('core', '0022_auto_20190116_1744'),
    ]

    operations = [
    ]
