# Generated by Django 2.1.5 on 2019-01-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190116_1741'),
        ('core', '0023_merge_20190117_0448'),
    ]

    operations = [
    ]
