# Generated by Django 2.1.5 on 2019-01-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190113_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='name',
        ),
    ]
