# Generated by Django 2.1.5 on 2019-01-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_mushroomspot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroomspot',
            old_name='location',
            new_name='geom',
        ),
    ]
