# Generated by Django 2.1.5 on 2019-01-18 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20190118_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavereview',
            name='event',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='leavereview',
            name='title',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='businesslatlong',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.Business'),
        ),
    ]
